apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: file_uploader
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/moosterhuis/FileUploader.git
    targetRevision: HEAD
    path: file_uploader_helm
  destination:
    server: https://kubernetes.default.svc
    namespace: default