apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: {{ .Values.frontend_deploy.image }}
          ports:
            - containerPort: 80
          env:
          - name: API_URL
            valueFrom:
              configMapKeyRef:
                name: frontend-config
                key: apiUrl